import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const src = path.resolve(here, '../src')
const read = relative => fs.readFileSync(path.join(src, relative), 'utf8')

test('render fidelity V3 uses an original layered archive assembly instead of a box-and-label card', () => {
  const assembly = read('analysis-os/render/archiveAssembly.js')

  assert.match(assembly, /RoundedBoxGeometry/)
  assert.match(assembly, /glassCover|const glass/)
  assert.match(assembly, /ringTop/)
  assert.match(assembly, /ringBottom/)
  assert.match(assembly, /centerBridge|const bridge/)
  assert.match(assembly, /fasteners/)
  assert.match(assembly, /decryptA/)
  assert.match(assembly, /decryptB/)
  assert.match(assembly, /MeshPhysicalMaterial/)
})

test('render fidelity V3 defines quality profiles, tone mapping and soft-shadow capability', () => {
  const quality = read('analysis-os/render/renderQuality.js')
  const scene = read('components/analysis/AnalysisArchiveScene.vue')

  assert.match(quality, /ACESFilmicToneMapping/)
  assert.match(quality, /PCFShadowMap/)
  assert.match(quality, /HIGH/)
  assert.match(quality, /BALANCED/)
  assert.match(quality, /MOBILE/)
  assert.match(scene, /HemisphereLight/)
  assert.match(scene, /focusedGlassMaterial\.transmission/)
  assert.match(quality, /shadows: true/)
  assert.match(scene, /renderer\.shadowMap\.enabled = false/)
})

test('archive night theme keeps the same geometry while applying Midnight Atelier materials and gallery light', () => {
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const assembly = read('analysis-os/render/archiveAssembly.js')
  const page = read('pages/AnalysisOsPage.vue')

  assert.match(scene, /night: Object\.freeze/)
  assert.match(scene, /background: '#0c1013'/)
  assert.match(scene, /exposure: 1\.26/)
  assert.match(scene, /ambientIntensity: 0\.38/)
  assert.match(scene, /rimColor: 0xb99e72/)
  assert.match(scene, /auroraColor: 0x8aa2a8/)
  assert.match(scene, /auroraIntensity: 0\.06/)
  assert.match(scene, /auroraLight = new DirectionalLight\(0x8aa2a8, 0\)/)
  assert.match(scene, /renderer\.toneMappingExposure = theme\.exposure/)
  assert.match(scene, /function applySceneTheme\(\)/)
  assert.match(scene, /scene\.background\?\.set/)
  assert.match(scene, /renderer\.setClearColor\(theme\.background, 1\)/)
  assert.match(scene, /watch\(\(\) => props\.nightMode/)
  assert.match(scene, /refreshLabelTextures\(\)/)
  assert.match(assembly, /body: Object\.freeze\(\{ color: '#33373a'/)
  assert.match(assembly, /frame: Object\.freeze\(\{ color: '#514c45'/)
  assert.match(assembly, /focusFrame: Object\.freeze\(\{ color: '#c2a777'/)
  assert.match(assembly, /focusAccent: Object\.freeze\(\{ color: '#d9bd87'/)
  assert.match(assembly, /focusMetal: Object\.freeze\(\{ color: '#9f9077'/)
  assert.match(assembly, /export function applyArchiveTheme/)
  assert.match(scene, /function updateBaseInstanceFocusColors\(\)/)
  assert.match(scene, /baseInstances\.body\.setColorAt\(entry\.instanceIndex/)
  assert.match(scene, /focusedBodyInstanceColor = new Color\('#fffdf8'\)/)
  assert.match(scene, /focusedInsetInstanceColor = new Color\('#fff8ec'\)/)
  assert.match(scene, /focusedMarkInstanceColor = new Color\('#dec08a'\)/)
  assert.match(scene, /archiveLibrary\.materials\.focusFrame/)
  assert.match(page, /'is-night': props\.nightMode/)
  assert.match(page, /Midnight Atelier/)
  assert.match(page, /class="archive-aurora"/)
  assert.match(page, /archive-aurora-drift/)
  assert.match(page, /archive-focus-breathe/)
  assert.match(page, /● NIGHT/)
  assert.doesNotMatch(page, /filter:\s*brightness\(/)
  assert.doesNotMatch(page, /backdrop-filter/)
})

test('optional post processing probes the GPU and falls back to direct rendering on WebGL errors', () => {
  const quality = read('analysis-os/render/renderQuality.js')
  const scene = read('components/analysis/AnalysisArchiveScene.vue')

  assert.match(quality, /probeArchiveComposer/)
  assert.match(quality, /gl\.getError\(\)/)
  assert.match(quality, /fallback-webgl/)
  assert.match(quality, /composer\.renderToScreen = false/)
  assert.match(quality, /renderer\.setRenderTarget\?\.\(previousTarget\)/)
  assert.doesNotMatch(quality, /BokehPass/)
  assert.match(quality, /maxDpr: 1\.75/)
  assert.match(quality, /renderScale: 1\.25/)
  assert.match(scene, /nativeDpr \* \(qualityProfile\.renderScale \|\| 1\)/)
  assert.match(quality, /renderer\.render\(scene, camera\)/)
  assert.match(scene, /postProcessingStatus/)
  assert.match(scene, /skipped-automation/)
  assert.match(scene, /schedulePostProcessingProbe/)
  assert.match(scene, /IDLE_RENDER_INTERVAL_MS = 1000 \/ 31/)
  assert.match(scene, /const STABLE_DIRECT_EXTRACTION = true/)
  assert.match(scene, /ssaoPass\.enabled = false/)
  assert.match(scene, /renderer\.render\(scene, camera\)/)
  assert.match(scene, /!STABLE_DIRECT_EXTRACTION/)
  assert.match(scene, /browseDetailDensity/)
  assert.doesNotMatch(scene, /focusArchiveComposer/)
})

test('boot and sound systems are original local runtime effects without third-party media assets', () => {
  const page = read('pages/AnalysisOsPage.vue')
  const audio = read('analysis-os/audio/useArchiveAudio.js')

  for (const stage of ['SYSTEM WAKE', 'IDENTITY RESOLVED', 'PERMISSION SCAN', 'MODULE ARCHIVE ONLINE']) {
    assert.match(page, new RegExp(stage))
  }
  assert.match(page, /bootPhase/)
  assert.match(page, /SOUND/)
  assert.match(audio, /AudioContext/)
  assert.match(audio, /createOscillator/)
  assert.match(audio, /createBuffer/)
  assert.doesNotMatch(audio, /fetch\(|\.mp3|\.wav|\.ogg/i)
})

test('render fidelity V3 extraction exposes glass-decrypt stages without moving the card toward the camera', () => {
  const page = read('pages/AnalysisOsPage.vue')
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const transition = read('analysis-os/motion/useArchiveTransition.js')
  const app = read('App.vue')

  assert.match(page, /RELEASE LOCK/)
  assert.match(page, /VERTICAL EXTRACTION/)
  assert.match(page, /CAMERA APPROACH/)
  assert.match(page, /GLASS DECRYPT/)
  assert.match(page, /DOCUMENT REVEAL/)
  assert.match(page, /WORKSPACE_HANDOFF_MS = 1420/)
  assert.match(page, /WORKSPACE_HANDOFF_REDUCED_MS = 180/)
  assert.match(page, /function animateWorkspaceHandoff/)
  assert.match(page, /handoffPhase\.value = progress < 0\.19/)
  assert.match(page, /props\.workspacePreload\?\.\(module\.routeKey, 'immediate'\)/)
  assert.match(page, /props\.workspacePreload\?\.\(module\.routeKey, 'idle'\)/)
  assert.match(page, /if \(!reducedMotion\) await waitForPaint\(\)/)
  assert.doesNotMatch(page, /setTimeout\(resolve, WORKSPACE_REVEAL_HOLD_MS/)
  assert.doesNotMatch(page, /clipPath:/)
  assert.match(page, /transform: `translate3d\(/)
  assert.match(page, /--handoff-scan-x/)
  assert.doesNotMatch(page, /backdrop-filter: blur\(2px\)/)
  assert.match(app, /const workspaceLoaders = Object\.freeze/)
  assert.match(app, /function preloadWorkspace\(routeKey, priority = 'idle'\)/)
  assert.match(app, /const preparedWorkspaceRoute = ref\(''\)/)
  assert.match(app, /const archiveHandoffHold = ref\(false\)/)
  assert.match(app, /const workspaceRenderRoute = computed/)
  assert.match(app, /const workspaceWarmers = Object\.freeze/)
  assert.match(app, /'行情': \(\) => import\('\.\/charts\/echarts'\)/)
  assert.match(app, /requestAnimationFrame\(\(\) => requestAnimationFrame\(resolve\)\)/)
  assert.match(app, /const workspaceRevealReady = ref\(true\)/)
  assert.match(app, /async function handleWorkspaceReady/)
  assert.match(app, /v-show="activeTab === '研究终端' \|\| archiveHandoffHold"/)
  assert.match(app, /:active="activeTab === '研究终端'"/)
  assert.match(app, /:active="Boolean\(activeModule\)"/)
  assert.match(app, /:revealed="workspaceRevealReady"/)
  assert.match(app, /v-if="workspaceRenderRoute === '行情'"/)
  assert.match(app, /:active="activeTab === '行情' && workspaceRevealReady"/)
  assert.match(app, /@ready="handleWorkspaceReady\('行情'\)"/)
  assert.match(app, /:active="activeTab === '多市场' && workspaceRevealReady"/)
  assert.match(app, /@ready="handleWorkspaceReady\('多市场'\)"/)
  assert.match(app, /archiveHandoffTimer = window\.setTimeout/)
  assert.match(app, /}, 320\)/)
  const shell = read('analysis-os/components/ArchiveWorkspaceShell.vue')
  assert.match(shell, /active: \{ type: Boolean, default: true \}/)
  assert.match(shell, /revealed: \{ type: Boolean, default: true \}/)
  assert.match(shell, /workspace-shell\.preparing/)
  assert.match(shell, /position: fixed; inset: 0; z-index: 100/)
  assert.match(shell, /transition: opacity \.28s/)
  assert.doesNotMatch(shell, /workspace-entry-bridge/)
  assert.doesNotMatch(shell, /entry-hud/)
  assert.match(app, /workspacePreloads = new Map/)
  assert.match(app, /window\.requestIdleCallback\(start\)/)
  assert.match(app, /:workspace-preload="preloadWorkspace"/)
  const market = read('pages/MarketPage.vue')
  const crossMarket = read('components/CrossMarketView.vue')
  const marketChart = read('composables/useMarketChart.js')
  assert.match(market, /await marketChart\.prepare\(\)/)
  assert.match(market, /emit\('ready'\)/)
  assert.match(crossMarket, /active: \{ type: Boolean, default: true \}/)
  assert.match(crossMarket, /bootstrapping = true/)
  assert.match(crossMarket, /await marketChart\.prepare\(\)/)
  assert.match(crossMarket, /emit\('ready'\)/)
  assert.match(marketChart, /prepare: chart\.ensureChart/)
  assert.match(page, /documentRevealAmount \* 1\.55/)
  assert.match(scene, /0\.40 \+ extraction \* \(4\.05 - 0\.40\)/)
  assert.match(scene, /camera\.position\.copy\(cameraBase\)\.lerp\(cameraDetailBase, detail\)/)
  assert.match(transition, /options\.enterDuration \|\| 1080/)
})

test('render fidelity V3-G uses an original focused GLB with procedural fallback', () => {
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const assetReadme = fs.readFileSync(path.resolve(here, '../public/assets/analysis-os/README.md'), 'utf8')

  assert.match(scene, /GLTFLoader/)
  assert.match(scene, /jarvis-archive-v1\.glb/)
  assert.match(scene, /detailAssetStatus = 'fallback'/)
  assert.match(scene, /qualityProfile\.name !== 'MOBILE'/)
  assert.match(scene, /disposeFocusedArchiveAsset/)
  assert.match(assetReadme, /original JARVIS archive model/)
})

test('archive field composition V5 matches the wide-card long-lens archive reference while keeping anonymous backgrounds', () => {
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const page = read('pages/AnalysisOsPage.vue')

  assert.match(scene, /const LANE_SPACING = 5\.20/)
  assert.match(scene, /const ROW_SPACING = 0\.62/)
  assert.match(scene, /const elevation = 7\.5 \* Math\.PI \/ 180/)
  assert.match(scene, /const LANE_ROW_SKEW = 0/)
  assert.match(scene, /const targetTilt = 0/)
  assert.match(scene, /function setDesktopBrowseCamera/)
  assert.match(scene, /const baseSpan = 7\.33/)
  assert.match(scene, /const distance = 100/)
  assert.match(scene, /const referenceDistance = 140/)
  assert.match(scene, /const yaw = 76\.75 \* Math\.PI \/ 180/)
  assert.match(scene, /cameraAimBase\.set\(-5\.13, -2\.16, 0\.481\)/)
  assert.match(scene, /0\.965 \+ extraction \* 0\.091/)
  assert.doesNotMatch(scene, /identified \? 1\.028/)
  assert.match(scene, /scene\.fog = new Fog\('#eae5e1', 145, 165\)/)
  assert.match(scene, /const renderedDistance = camera\.position\.distanceTo\(cameraAim\)/)
  assert.match(scene, /archiveShoulderField/)
  assert.match(scene, /ANONYMOUS_ARCHIVE/)
  assert.match(scene, /showIdentity = Boolean\(isFocused && identified\)/)
  assert.match(scene, /retrievalState/)
  assert.match(scene, /const shoulder = archiveShoulderField\(rowRelative, laneRelative\)/)
  assert.match(scene, /radial-gradient\(ellipse at 48% 48%/)
  assert.doesNotMatch(scene, /moduleAtCell|cellForModule/)
  assert.match(page, /moduleIndexExpanded/)
  assert.match(page, /module-index-shell\.expanded/)
  assert.match(page, /FILE NUMBER:/)
})

test('archive sea V5 uses bidirectional cyclic flow and a lightweight retrieval illusion', () => {
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const page = read('pages/AnalysisOsPage.vue')

  assert.match(scene, /emit\('step', delta\)/)
  assert.match(scene, /emit\('settled'\)/)
  assert.match(scene, /function shiftRows/)
  assert.match(page, /wrap\(focusedIndex\.value \+ delta, modules\.length\)/)
  assert.match(page, /retrievalState\.value = 'FLOW'/)
  assert.match(page, /retrievalState\.value = 'QUERY'/)
  assert.match(page, /retrievalState\.value = 'MATCH'/)
  assert.match(page, /archive-callout/)
  assert.match(page, /is-settled/)
  assert.doesNotMatch(page, /class="retrieval-hud"/)
  assert.doesNotMatch(page, /PseudoRandomArchiveResolver|candidateScore|randomCandidate/i)
})

test('archive browse keeps visual density restrained and avoids stop-state detail pops', () => {
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const page = read('pages/AnalysisOsPage.vue')
  const assembly = read('analysis-os/render/archiveAssembly.js')

  assert.match(scene, /let motionAmount = 0/)
  assert.match(scene, /let detailDensity = 0\.42/)
  assert.match(scene, /let settleProgress = 1/)
  assert.match(scene, /function detailBudgetForState/)
  assert.match(scene, /densityBudget = Math\.max\(2, Math\.min\(6, Math\.round\(1 \+ detailDensity \* 12\)\)\)/)
  assert.match(scene, /if \(props\.retrievalState === 'FLOW'\) return Math\.min\(3, densityBudget\)/)
  assert.match(scene, /Math\.min\(4 \+ Math\.round\(settleProgress \* 2\), densityBudget\)/)
  assert.match(scene, /const DETAIL_RETENTION_BIAS = 0\.34/)
  assert.match(scene, /retainedNearDetail\.has\(entry\) \? DETAIL_RETENTION_BIAS : 0/)
  assert.match(scene, /const tracksResting = Math\.abs\(laneTrack\.value - laneTrack\.target\) < 0\.00002/)
  assert.match(scene, /time - settledAt > 1200/)
  assert.match(scene, /const FRAME_DETAIL_BUDGET = 6/)
  assert.match(scene, /const FRAME_RETENTION_BIAS = 0\.48/)
  assert.match(scene, /renderer\.initTexture\?\.\(texture\)/)
  assert.match(scene, /entry\.frameGroup\.visible = hasFrame/)
  assert.match(assembly, /frameGroup\.add\(left, right, top, bottom\)/)
  assert.match(assembly, /glass: new RoundedBoxGeometry\(4\.46, 3\.18/)
  assert.match(scene, /new InstancedMesh/)
  assert.match(scene, /baseInstances\.body\.setMatrixAt/)
  assert.match(scene, /const USE_FOCUSED_GLB_IN_TRANSITION = false/)
  assert.match(scene, /const focusPreviewVisible = \(isFocused && \(props\.retrievalState === 'FOCUSED' \|\| extraction > 0\.001\)\)/)
  assert.match(scene, /child\.visible = !focusedDetailActive && !child\.userData\?\.archiveGlassEdge/)
  assert.match(scene, /entry\.marker\.visible = showIdentity && !focusedDetailActive/)
  assert.match(scene, /entry\.labelCarrier\.visible = showIdentity && !focusedDetailActive/)
  assert.doesNotMatch(scene, /const idle = .*Math\.sin/)
  assert.doesNotMatch(scene, /const sleepWave =/)
  assert.doesNotMatch(scene, /const idleTilt =/)
  assert.match(scene, /const shoulderLane = sleep\.amount > 0 \? laneTrack\.value : visualLane/)
  assert.match(scene, /const shoulderRow = sleep\.amount > 0 \? rowTrack\.value : visualRow/)
  assert.match(scene, /lane: Math\.sin\(time \/ 13_000\) \* 0\.18 \* amount/)
  assert.match(scene, /Math\.abs\(yDelta\) < 0\.00035/)
  assert.match(scene, /Math\.abs\(scaleDelta\) < 0\.00005/)
  assert.match(scene, /detailVisible = USE_FOCUSED_GLB_IN_TRANSITION/)
  assert.match(scene, /const focusedDetailActive = Boolean\(/)
  assert.match(scene, /props\.retrievalState === 'FOCUSED'/)
  assert.match(scene, /entry\.frameGroup\.visible = hasFrame && !focusedDetailActive/)
  assert.match(scene, /entry\.nearGroup\.visible = isNear && !focusedDetailActive/)
  assert.match(scene, /if \(focusedDetailActive\) \{/)
  assert.match(assembly, /edge\.userData\.archiveGlassEdge = true/)
  assert.match(assembly, /edge\.visible = false/)
  assert.match(scene, /entry\.body\.castShadow = false/)
  assert.match(scene, /keyLight\.castShadow = false/)
  assert.match(assembly, /left\.position\.set\(-2\.30, 0, 0\.285\)/)
  assert.match(assembly, /right\.position\.set\(2\.30, 0, 0\.285\)/)
  assert.match(assembly, /top\.position\.set\(0, 1\.65, 0\.285\)/)
  assert.match(assembly, /railL\.position\.set\(-1\.06, -0\.18, 0\.275\)/)
  assert.match(assembly, /glass\.visible = false/)
  assert.doesNotMatch(assembly, /polygonOffset/)
  assert.doesNotMatch(scene, /keyLight\.castShadow = Boolean\(qualityProfile\?\.shadows && !interactiveMotion\)/)
  assert.match(page, /const settleProgress = ref\(1\)/)
  assert.match(page, /calloutFileOpacity/)
  assert.match(page, /calloutNameOpacity/)
  assert.match(page, /calloutCtaOpacity/)
  assert.match(page, /:disabled="!calloutCtaReady"/)
  assert.match(page, /@motion="handleSceneMotion"/)
  assert.doesNotMatch(page, /module-summary/)
  assert.doesNotMatch(page, /capability-line/)
})

test('archive sea V5 has no visible physical edge because the finite pool is periodically remapped', () => {
  const scene = read('components/analysis/AnalysisArchiveScene.vue')
  const loop = read('analysis-os/motion/archiveLoop.js')

  assert.match(scene, /LOOP_POOL/)
  assert.match(loop, /laneCount: 11/)
  assert.match(loop, /rowCount: 35/)
  assert.match(scene, /updateWrappedArchivePositions/)
  assert.match(scene, /entry\.virtualLane/)
  assert.match(scene, /entry\.virtualRow/)
  assert.match(scene, /poolKeyForCell/)
  assert.match(loop, /nearestPeriodicCoordinate/)
  assert.match(loop, /canonicalPoolCoordinate/)
  assert.doesNotMatch(scene, /root\.position\.x = -\(laneTrack/)
  assert.doesNotMatch(scene, /root\.position\.z = -\(rowTrack/)
})

