import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const app = fs.readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')
const shell = fs.readFileSync(new URL('../src/analysis-os/components/ArchiveWorkspaceShell.vue', import.meta.url), 'utf8')
const archive = fs.readFileSync(new URL('../src/pages/AnalysisOsPage.vue', import.meta.url), 'utf8')
const scene = fs.readFileSync(new URL('../src/components/analysis/AnalysisArchiveScene.vue', import.meta.url), 'utf8')
const assembly = fs.readFileSync(new URL('../src/analysis-os/render/archiveAssembly.js', import.meta.url), 'utf8')
const index = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8')

test('day/night theme is global, migrated and restored before Vue paints', () => {
  assert.match(index, /jarvis-theme/)
  assert.match(index, /jarvis-ui-night-mode/)
  assert.match(index, /document\.documentElement\.dataset\.theme = theme/)
  assert.match(app, /const THEME_MODE_KEY = 'jarvis-theme'/)
  assert.match(app, /const LEGACY_NIGHT_MODE_KEY = 'jarvis-ui-night-mode'/)
  assert.match(app, /localStorage\.setItem\(THEME_MODE_KEY, theme\)/)
  assert.match(app, /document\.documentElement\.dataset\.theme = theme/)
  assert.match(app, /:night-mode="nightMode"/)
  assert.match(app, /@toggle-night-mode="toggleNightMode"/)
  assert.match(shell, /@click="emit\('toggle-night-mode'\)"/)
  assert.match(shell, /:aria-pressed="props\.nightMode"/)
  assert.match(shell, /\.workspace-shell\.is-night\s*\{/)
  assert.match(shell, /--bg: #0b0f13/)
})

test('archive workspace shares the global theme and mutates WebGL resources in place', () => {
  assert.match(archive, /nightMode: \{ type: Boolean, default: false \}/)
  assert.match(archive, /'is-night': props\.nightMode/)
  assert.match(archive, /@click="emit\('toggle-night-mode'\)"/)
  assert.match(archive, /:night-mode="props\.nightMode"/)
  assert.match(archive, /Midnight Atelier/)
  assert.match(archive, /--paper: #0c1013/)
  assert.match(archive, /--ink: #eee8de/)
  assert.match(archive, /--accent: #ad956d/)
  assert.match(archive, /class="archive-aurora"/)
  assert.match(scene, /nightMode: \{ type: Boolean, default: false \}/)
  assert.match(scene, /function applySceneTheme\(\)/)
  assert.match(scene, /watch\(\(\) => props\.nightMode/)
  assert.match(scene, /applyArchiveTheme\(archiveLibrary, mode, focusedGlassMaterial\)/)
  assert.match(scene, /renderer\.toneMappingExposure = theme\.exposure/)
  assert.match(scene, /auroraLight\.intensity = theme\.auroraIntensity/)
  assert.doesNotMatch(scene, /watch\(\(\) => props\.nightMode[\s\S]{0,220}init\(\)/)
  assert.match(assembly, /export function applyArchiveTheme/)
  assert.match(assembly, /night: Object\.freeze/)
  assert.match(assembly, /#d9bd87/)
  assert.doesNotMatch(archive, /filter:\s*brightness\(/)
  assert.doesNotMatch(archive, /backdrop-filter/)
})
